branch-defaults:
  default:
    environment: just-tech-news-env
    group_suffix: null
global:
  application_name: just-tech-news
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
